---
extends: default

rules:
  line-length:
    max: 100
    level: error
  
  new-lines: false

  comments:
    require-starting-space: false
    min-spaces-from-content: 1

  comments-indentation:
    ignore: |
      .pre-commit-config.yaml
